version: "3"
services:
  maven:
    image: zinglix/freshfoodstore:0.0.1
    volumes:
      - ./application.properties:/config/application.properties
    container_name: freshfoodstore
    expose:
      - "8080"
    networks:
      - nginx_default
      - mysql_default
networks:
  nginx_default:
    external: true
  mysql_default:
    external: true
